name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "CI Running"

      - name: Create artifact file
        run: echo "This is my CI artifact" > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifact
          path: artifact.txt
